### ISSUE TITLE
dotnet run failed

### ISSUE THREAD

**Issue by isaaclem** [dsuryd/dotnetify-react-native-demo#16]
Hi when I executed `dotnet run`, I see the below stacktrace

```
Using launch settings from /Users/isaaclem/Code/react-native/dotnetify-react-native-demo/server/Properties/launchSettings.json...
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.Net.Sockets.SocketException (49): Can't assign requested address
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
```

And when I run the command `dotnet --version`, I see `2.1.301`.
I'm not sure if 2.1.301 is not supported?

However when I visit https://dotnet.microsoft.com/download/dotnet-core/2.1 I see this is the closest version?

**Comment by dsuryd** [comment]
That looks like problem with .NET Core server binding to your local port.  Are you running on Mac/Linux?  Try give it root permission.   If the issue persists, not sure I can help more; you should try the ASP.NET Core issue forum.

**Comment by glittle** [comment]
@isaaclem I found that the `launchSettings.json` file has an "applicationUrl" setting that you likely need to change to something valid for your computer.
